a l'aide

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -37,10 +37,16 @@ jobs:
           aws ecr get-login-password --region $AWS_REGION |
             docker login --username AWS --password-stdin $ECR_FRONTEND
 
+      - name: List files in workspace
+        run: ls -R
+
       - name: Build and Push Backend Image
-        working-directory: projet-aws-devops/backend
         run: |
-          docker build -t backend:latest -f Dockerfile .
+          if [ ! -d "projet-aws-devops/backend" ]; then
+            echo "Error: Directory projet-aws-devops/backend does not exist.";
+            exit 1;
+          fi
+          docker build -t backend:latest -f projet-aws-devops/backend/Dockerfile projet-aws-devops/backend
           docker tag backend:latest $ECR_BACKEND:latest
           docker push $ECR_BACKEND:latest
 
