a l'aide

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -35,6 +35,9 @@ jobs:
           aws ecr get-login-password --region $AWS_REGION \
             | docker login --username AWS --password-stdin $ECR_FRONTEND
 
+      - name: List files in workspace
+        run: ls -R
+
       - name: Validate frontend package.json
         working-directory: projet-aws-devops/frontend
         run: npm install --dry-run
@@ -46,9 +49,13 @@ jobs:
       - name: Build & Push backend image
         working-directory: projet-aws-devops/backend
         run: |
+          if [ ! -d "projet-aws-devops/backend" ]; then
+            echo "Error: Directory projet-aws-devops/backend does not exist.";
+            exit 1;
+          fi
           docker build \
             -t backend:latest \
-            -f Dockerfile \
+            -f Dockerfile .
           docker tag backend:latest $ECR_BACKEND:latest
           docker push $ECR_BACKEND:latest
 
@@ -57,7 +64,7 @@ jobs:
         run: |
           docker build \
             -t frontend:latest \
-            -f Dockerfile \
+            -f Dockerfile .
           docker tag frontend:latest $ECR_FRONTEND:latest
           docker push $ECR_FRONTEND:latest
 
